sudo: false

language: c

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - ghc-7.10.3
      - cabal-install-1.22

before_install:
  - export PATH=$HOME/.tinc/bin:/opt/ghc/7.10.3/bin:/opt/cabal/1.22/bin:$PATH
  - curl -sSL https://github.com/sol/tinc/raw/master/get-tinc.sh | bash
  - tinc --version
  - ghc --version
  - cabal --version
  - travis_retry cabal update
  - sed -i 's/^jobs:/-- jobs:/' ${HOME}/.cabal/config

install:
  - tinc

script:
  - cabal configure --enable-tests --ghc-options=-Werror && cabal build && cabal test

cache:
  directories:
    - $HOME/.tinc/cache
